version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18.x
    commands:
      - echo "Installing dependencies..."
      - npm install
      - echo "Installed packages:"
      - npm list --depth=0
  build:
    commands:
      - echo "Navigating to source directory..."
      - cd $CODEBUILD_SRC_DIR
      - echo "Current directory:"
      - pwd
      - echo "Contents of the directory:"
      - ls -la
      - echo "Contents of package.json:"
      - cat package.json
      - echo "NPM version:"
      - npm -v
      - echo Running tests...
      - npm run test

artifacts:
  base-directory: '.next'
  files:
    - '**/*'
    - 'reports/**/*'