version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18.x
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo "Current directory:"
      - pwd
      - echo "Contents of the directory:"
      - ls -la
      - echo "Installed packages:"
      - npm list --depth=0
      - echo "Node version:"
      - node -v
      - echo "NPM version:"
      - npm -v
      - echo Running tests...
      - npm test
      - echo "Building the application..."
      - npm run build
      - echo "Contents of the .next directory:"
      - ls -la .next
  post_build:
    commands:
      - echo "Build complete."

artifacts:
  base-directory: .next
  files:
    - '**/*'
    - 'reports/**/*'
