version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18.x
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Building the application..."
      - npm run build
      - ls -la .next

  post_build:
    commands:
      - echo "Running tests..."
      - npm run test
      - echo "Build and test complete."

artifacts:
  base-directory: '.next'
  files:
    - '**/*'
    - 'reports/**/*'